version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.repo_name}}"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: ptpython
    versions:
    - 3.0.13
    - 3.0.7
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: pytest-cov
    versions:
    - 2.10.1
  - dependency-name: pylint
    versions:
    - 2.6.0
