[tool.poetry]
name = "{{ cookiecutter.repo_name }}"
version = "0.0.1"
description = ""
authors = ["{{ cookiecutter.full_name }} {{ cookiecutter.email }}"]
license = "MIT"

# Remember to run `poetry update` instead of `poetry install` on the first go!
[tool.poetry.dependencies]
python = ">3.8"
Django = "4.*"

[tool.poetry.dev-dependencies]
django-extensions = "3.*"
pytest = "7.*"
pytest-clarity = "1.*"
pytest-cov = "4.*"
pytest-django = "4.*"
coverage = "7.*"
django-coverage-plugin = "3.*"
black = "23.*"
mypy = "1.*"
mypy-extensions = "1.*"
pylint = "2.*"
pylint-django = "2.*"
ptpython = "3.*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
